version: '3.7'

services:
  database:
    image: postgres
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data

  api-grpc:
    build:
      context: .
      dockerfile: Dockerfile
    command: pnpm start:api-grpc:prod
    env_file:
      - .env
    depends_on:
      - database
    ports:
      - 5000:5000

  api-rest:
    build:
      context: .
      dockerfile: Dockerfile
    command: pnpm start:api-rest:prod
    env_file:
      - .env
    depends_on:
      - database
    ports:
      - ${NODE_PORT}:${NODE_PORT}
