version: '3.7'
services:
  database:
    image: postgres
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data

  api-graphql:
    build:
      target: api-graphql
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - database
    ports:
      - 5001:3000

  api-grpc:
    build:
      target: api-grpc
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - database
    ports:
      - 5002:5002

  api-rest:
    build:
      target: api-rest
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - database
    ports:
      - 3000:3000
