version: '3.7'

services:
  database:
    image: postgres
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data

  api-graphql:
    build:
      target: api-graphql
      context: .
      dockerfile: Dockerfile
    command: ls lib
    env_file:
      - .env
    depends_on:
      - database
    ports:
      - 5001:5001

  api-grpc:
    build:
      target: api-grpc
      context: .
      dockerfile: Dockerfile
    command: pnpm start:prod
    env_file:
      - .env
    depends_on:
      - database
    ports:
      - 5002:5002

  api-rest:
    build:
      target: api-rest
      context: .
      dockerfile: Dockerfile
    command: pnpm start:prod
    env_file:
      - .env
    depends_on:
      - database
    ports:
      - ${NODE_PORT}:${NODE_PORT}
