name: Build

on:
  pull_request:
    branches: 
    - '*'
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Setup PNPM and install dependencies
      uses: pnpm/action-setup@v2.2.2
      with:
        version: 6.31.0
        run_install: true

    - name: Install dependencies
      run: pnpm ci

    - name: Check Format
      run: pnpm format:check

    - name: Check Linter
      run: pnpm linter

    - name: Build
      run: pnpm build

    - name: Check Tests
      run: pnpm test:js:ci:coverage

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.COVERALLS_TOKEN }}
