name: Build

on:
  pull_request:
    branches: 
    - '*'
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci

    - name: Check Format
      run: npm run format:check

    - name: Check Linter
      run: npm run linter

    - name: Build
      run: npm run build

    - name: Check Tests
      run: npm run test:js:ci:coverage

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.COVERALLS_TOKEN }}
