name: CI

on:
  pull_request:
    branches: 
    - '*'
  push:
    branches:
    - main
    - develop
    
jobs: 
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
      - uses: actions/checkout@v3

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 6

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: package.json
      
      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Cache build
        id: cache-build
        uses: actions/cache@v3
        with:
          path: dist
          key: ${{ runner.os }}-build-${{ github.sha }}

  format:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
      - uses: actions/checkout@v3

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 6

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: package.json
      
      - name: Install dependencies
        run: pnpm install

      - name: Check Format
        run: pnpm format:check

  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
      - uses: actions/checkout@v3

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 6

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: package.json
      
      - name: Install dependencies
        run: pnpm install

      - name: Check Linter
        run: pnpm lint

  test:
    runs-on: ubuntu-latest
    needs: [build, format, lint]

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 6

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: package.json
      
      - name: Install dependencies
        run: pnpm install
      
      - name: Cache build
        id: cache-build
        uses: actions/cache@v3
        with:
          path: dist
          key: ${{ runner.os }}-build-${{ github.sha }}

      - name: Build
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: pnpm build
      
      - name: Check Tests
        run: pnpm test:js:ci:coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
