name: Create release

on: 
  workflow_dispatch:
    
jobs:
  create-release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.4.0
        with:
          version: latest

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: package.json

      - name: Install standard-version and conventional-changelog
        run : pnpm i -g standard-version conventional-changelog-cli

      - name: Config git
        run: |
          git config --global user.email "${{ github.event.sender.email }}"
          git config --global user.name "${{ github.event.sender.login }}"

      - name: Create changelog
        id: changelog
        run: >-
          echo "::set-output name=CHANGELOG::$(
            conventional-changelog -p conventionalcommits
          )"
          
      - name: Apply standard-version
        run: |
          standard-version -t ""  --no-verify --first-release

      - name: Get new version
        id: version
        run: >-
          echo "::set-output name=VERSION::$(
            jq .version package.json -r
          )"
      
      - name: Fix packages
        run: |
          jq --indent 2 '.version = "${{ steps.version.outputs.VERSION }}"' packages/api-graphql/package.json > packages/api-graphql/package.json
          jq --indent 2 '.version = "${{ steps.version.outputs.VERSION }}"' packages/api-grpc/package.json > packages/api-grpc/package.json
          jq --indent 2 '.version = "${{ steps.version.outputs.VERSION }}"' packages/api-rest/package.json > packages/api-rest/package.json
          jq --indent 2 '.version = "${{ steps.version.outputs.VERSION }}"' packages/core/package.json > packages/core/package.json
          cat packages/core/package.json
          
      - name: Commit release
        run: |
          git add .
          git status
          git commit --amend --no-verify --no-edit

      # - name: Create release
      #   run: |
      #     gh release create ${{ steps.version.outputs.VERSION }} --notes "${{ steps.changelog.outputs.CHANGELOG }}"
        
      
