name: Create release

on: 
  workflow_dispatch:
    
jobs:
  create-release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.4.0
        with:
          version: latest

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: package.json

      - name: Install standard-version and conventional-changelog
        run : pnpm i -g standard-version conventional-changelog-cli

      - name: Config git
        run: |
          git config --global user.email "${{ github.event.sender.email }}"
          git config --global user.name "${{ github.event.sender.login }}"

      - name: Create changelog
        id: changelog
        run: >-
          echo "::set-output name=CHANGELOG::$(
            conventional-changelog -p conventionalcommits
          )"
          
      - name: Apply standard-version
        run: |
          cd packages/api-graphql
          standard-version -t ""  --no-verify --first-release

      - name: Apply standard-version
        run: |
          cd packages/api-grpc
          standard-version -t ""  --no-verify --first-release

      - name: Apply standard-version
        run: |
          cd packages/api-rest
          standard-version -t ""  --no-verify --first-release

      - name: Apply standard-version
        run: |
          cd packages/core
          standard-version -t ""  --no-verify --first-release

      - name: Commit release
        run: |
          git commit --amend --no-verify --no-edit
          git push --no-verify
      
